#!/usr/bin/env bash
FROM node:16 as builder
WORKDIR /app
COPY ./ReactWebApp/package.json .
COPY ./ReactWebApp/package*.json .
RUN npm install
COPY ReactWebApp/ .
RUN npm run build
FROM node:16
WORKDIR /app
COPY ./SocketServer/ .
RUN npm install
COPY --from=builder /app/build/ ./build
EXPOSE 80
CMD ["node", "express_server.js"]