# Confluent configurations
CONFLUENT_QUESTION_TOPIC = "Questions"
CONFLUENT_ANSWER_TOPIC = "Answers"

# Rockset DB configuration
ROCKSET_API_KEY = ""
ROCKSET_API_SERVER = "https://api.use1a1.rockset.com"
FLIGHT_COLLECTION = "FlightData"
POLICY_COLLECTION = "FlightPolicy"
LOOKUP_COLLECTION = "FlightCode"

# Azure OpenAI configuration
AZURE_OPENAI_API_KEY = ""
AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME = ""
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME = ""
AZURE_OPENAI_API_VERSION = ""
